In [11]:
from urllib.request import urlopen
import json
import pandas as pd

df = pd.read_json('https://data.cityofchicago.org/resource/9xs2-f89t.json')

#Get df metadata
list(df)

['school_id',
 'name_of_school',
 'elementary_or_high_school',
 'street_address',
 'city',
 'state',
 'zip_code',
 'phone_number',
 'link_',
 'network_manager',
 'collaborative_name',
 'adequate_yearly_progress_made_',
 'track_schedule',
 'cps_performance_policy_status',
 'cps_performance_policy_level',
 'healthy_schools_certified_',
 'safety_icon_',
 'safety_score',
 'family_involvement_icon',
 'family_involvement_score',
 'environment_icon_',
 'environment_score',
 'instruction_icon_',
 'instruction_score',
 'leaders_icon_',
 'leaders_score_',
 'teachers_icon_',
 'teachers_score',
 'parent_engagement_icon_',
 'parent_engagement_score',
 'parent_environment_icon',
 'parent_environment_score',
 'average_student_attendance',
 'rate_of_misconducts_per_100_students_',
 'average_teacher_attendance',
 'individualized_education_program_compliance_rate_',
 'pk_2_literacy',
 'pk_2_math_',
 'gr3_5_grade_level_math',
 'gr3_5_grade_level_read_',
 'gr3_5_keep_pace_read_',
 'gr3_5_keep_pace_math',
 'gr6_8_grade_level_math',
 'gr6_8_grade_level_read',
 'gr6_8_keep_pace_math',
 'gr6_8_keep_pace_read',
 'gr_8_explore_math',
 'gr_8_explore_read',
 'isat_exceeding_math_',
 'isat_exceeding_reading_',
 'isat_value_add_math',
 'isat_value_add_read',
 'isat_value_add_color_math',
 'isat_value_add_color_read',
 'students_taking_algebra',
 'students_passing_algebra',
 '_th_grade_explore_2009_',
 '_th_grade_explore_2010_',
 '_th_grade_plan_2009_',
 '_th_grade_plan_2010_',
 'net_change_explore_and_plan',
 '_th_grade_average_act_2011_',
 'net_change_plan_and_act',
 'college_eligibility_',
 'graduation_rate_',
 'college_enrollment_rate',
 'college_enrollment_number_of_students_',
 'general_services_route_',
 'freshman_on_track_rate',
 'rcdts_code',
 'x_coordinate',
 'y_coordinate',
 'latitude',
 'longitude',
 'community_area_number',
 'community_area_name',
 'ward',
 'police_district',
 'location',
 ':@computed_region_rpca_8um6',
 ':@computed_region_vrxf_vc4k',
 ':@computed_region_6mkv_f3dw',
 ':@computed_region_bdys_3d7i',
 ':@computed_region_43wa_7qmu',
 ':@computed_region_awaf_s7ux']

In [12]:
#Cut unnecessary columns
df.drop(columns=[ ':@computed_region_rpca_8um6',
 ':@computed_region_vrxf_vc4k',
 ':@computed_region_6mkv_f3dw',
 ':@computed_region_bdys_3d7i',
 ':@computed_region_43wa_7qmu',
 ':@computed_region_awaf_s7ux'], axis=1, inplace=True)

In [13]:
#Connect to SQL 
import psycopg2
import IPython
import pandas.io.sql as sqlio
import psycopg2

%load_ext sql
%sql postgresql+psycopg2://postgres:5677@/IBM_SQL

#Check connection with SQL query
%%sql
SELECT * FROM information_schema.tables

SyntaxError: invalid syntax (Temp/ipykernel_20584/1936466199.py, line 12)

In [ ]:
%%sql
SELECT * FROM information_schema.tables

In [ ]:
%load_ext sql
%sql postgresql+psycopg2://postgres:5677@/IBM_SQL

In [ ]:
%%sql
SELECT * FROM information_schema.tables

In [ ]:
engine = create_engine('postgresql://postgres:5677@/IBM_SQL')

In [ ]:
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('postgresql://postgres:5677@/IBM_SQL')

In [ ]:
df['link_'] = df['link_'].str.replace("{'url': ","")
df['link_'] = df['link_'].str.replace("}","")

In [ ]:
df['link_'] = df['link_'].astype('str') 
df['link_'] = df['link_'].str.replace("{'url': ","")
df['link_'] = df['link_'].str.replace("}","")

In [14]:
df.head(5)

,school_id,name_of_school,elementary_or_high_school,street_address,city,state,zip_code,phone_number,link_,network_manager,...,rcdts_code,x_coordinate,y_coordinate,latitude,longitude,community_area_number,community_area_name,ward,police_district,location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,{'url': 'http://schoolreports.cps.edu/SchoolPr...,Fullerton Elementary Network,...,150000000000000,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"{'latitude': '41.92449696', 'longitude': '-87...."
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,{'url': 'http://schoolreports.cps.edu/SchoolPr...,Skyway Elementary Network,...,150000000000000,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"{'latitude': '41.76032435', 'longitude': '-87...."
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,{'url': 'http://schoolreports.cps.edu/SchoolPr...,Midway Elementary Network,...,150000000000000,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"{'latitude': '41.74711093', 'longitude': '-87...."
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,{'url': 'http://schoolreports.cps.edu/SchoolPr...,Pershing Elementary Network,...,150000000000000,1164504.290,1873959.199,41.809757,-87.672145,61,NEW CITY,20,9,"{'latitude': '41.8097569', 'longitude': '-87.6..."
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,{'url': 'http://schoolreports.cps.edu/SchoolPr...,Southwest Side High School Network,...,150000000000000,1175177.622,1880745.126,41.828146,-87.632794,34,ARMOUR SQUARE,11,9,"{'latitude': '41.82814609', 'longitude': '-87...."

In [15]:
for column in df:
    df[column] = df[column].apply(json.dumps)

In [16]:
df.head(5)

,school_id,name_of_school,elementary_or_high_school,street_address,city,state,zip_code,phone_number,link_,network_manager,...,rcdts_code,x_coordinate,y_coordinate,latitude,longitude,community_area_number,community_area_name,ward,police_district,location
0,610038,"""Abraham Lincoln Elementary School""","""ES""","""615 W Kemper Pl ""","""Chicago""","""IL""",60614,"""(773) 534-5720""","{""url"": ""http://schoolreports.cps.edu/SchoolPr...","""Fullerton Elementary Network""",...,150000000000000,1171699.458,1915829.428,41.92449696,-87.64452163,7,"""LINCOLN PARK""",43,18,"{""latitude"": ""41.92449696"", ""longitude"": ""-87...."
1,610281,"""Adam Clayton Powell Paideia Community Academy...","""ES""","""7511 S South Shore Dr ""","""Chicago""","""IL""",60649,"""(773) 535-6650""","{""url"": ""http://schoolreports.cps.edu/SchoolPr...","""Skyway Elementary Network""",...,150000000000000,1196129.985,1856209.466,41.76032435,-87.55673627,43,"""SOUTH SHORE""",7,4,"{""latitude"": ""41.76032435"", ""longitude"": ""-87...."
2,610185,"""Adlai E Stevenson Elementary School""","""ES""","""8010 S Kostner Ave ""","""Chicago""","""IL""",60652,"""(773) 535-2280""","{""url"": ""http://schoolreports.cps.edu/SchoolPr...","""Midway Elementary Network""",...,150000000000000,1148427.165,1851012.215,41.74711093,-87.73170248,70,"""ASHBURN""",13,8,"{""latitude"": ""41.74711093"", ""longitude"": ""-87...."
3,609993,"""Agustin Lara Elementary Academy""","""ES""","""4619 S Wolcott Ave ""","""Chicago""","""IL""",60609,"""(773) 535-4389""","{""url"": ""http://schoolreports.cps.edu/SchoolPr...","""Pershing Elementary Network""",...,150000000000000,1164504.29,1873959.199,41.8097569,-87.6721446,61,"""NEW CITY""",20,9,"{""latitude"": ""41.8097569"", ""longitude"": ""-87.6..."
4,610513,"""Air Force Academy High School""","""HS""","""3630 S Wells St ""","""Chicago""","""IL""",60609,"""(773) 535-1590""","{""url"": ""http://schoolreports.cps.edu/SchoolPr...","""Southwest Side High School Network""",...,150000000000000,1175177.622,1880745.126,41.82814609,-87.63279369,34,"""ARMOUR SQUARE""",11,9,"{""latitude"": ""41.82814609"", ""longitude"": ""-87...."

In [17]:
df = df.replace('"', '', regex=True)

In [18]:
df.head(5)

,school_id,name_of_school,elementary_or_high_school,street_address,city,state,zip_code,phone_number,link_,network_manager,...,rcdts_code,x_coordinate,y_coordinate,latitude,longitude,community_area_number,community_area_name,ward,police_district,location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,{url: http://schoolreports.cps.edu/SchoolProgr...,Fullerton Elementary Network,...,150000000000000,1171699.458,1915829.428,41.92449696,-87.64452163,7,LINCOLN PARK,43,18,"{latitude: 41.92449696, longitude: -87.64452163}"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,{url: http://schoolreports.cps.edu/SchoolProgr...,Skyway Elementary Network,...,150000000000000,1196129.985,1856209.466,41.76032435,-87.55673627,43,SOUTH SHORE,7,4,"{latitude: 41.76032435, longitude: -87.55673627}"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,{url: http://schoolreports.cps.edu/SchoolProgr...,Midway Elementary Network,...,150000000000000,1148427.165,1851012.215,41.74711093,-87.73170248,70,ASHBURN,13,8,"{latitude: 41.74711093, longitude: -87.73170248}"
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,{url: http://schoolreports.cps.edu/SchoolProgr...,Pershing Elementary Network,...,150000000000000,1164504.29,1873959.199,41.8097569,-87.6721446,61,NEW CITY,20,9,"{latitude: 41.8097569, longitude: -87.6721446}"
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,{url: http://schoolreports.cps.edu/SchoolProgr...,Southwest Side High School Network,...,150000000000000,1175177.622,1880745.126,41.82814609,-87.63279369,34,ARMOUR SQUARE,11,9,"{latitude: 41.82814609, longitude: -87.63279369}"

In [19]:
df.to_sql('chicago', engine)

In [20]:
%%sql

UsageError: %%sql is a cell magic, but the cell body is empty. Did you mean the line magic %sql (single %)?

In [21]:
%%sql
select * from chicago where name_of_school='Agustin Lara Elementary Academy'

 * postgresql+psycopg2://postgres:***@/IBM_SQL
1 rows affected.

[(3, '609993', 'Agustin Lara Elementary Academy', 'ES', '4619 S Wolcott Ave ', 'Chicago', 'IL', '60609', '(773) 535-4389', '{url: http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609993.pdf}', 'Pershing Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', '56.0', 'Average', '44', 'Average', '45.0', 'Weak', '37.0', 'Strong', '65', 'Average', '48', 'Average', '53', 'Strong', '58', '95.5', '10.4', '95.8', '100.0', '76.9', 'NDA', '26', '24.7', '61.8', '49.7', '39.2', '27.2', '69.7', '60.6', '9.1', '18.2', '11.1', '9.6', '0.9', '2.4', 'Green', 'Green', '42.9', '25', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '556', '42', 'NDA', '150000000000000', '1164504.29', '1873959.199', '41.8097569', '-87.6721446', '61', 'NEW CITY', '20', '9', '{latitude: 41.8097569, longitude: -87.6721446}')]