In [1]:
from urllib.request import urlopen
import json
import pandas as pd

df = pd.read_json('https://data.cityofchicago.org/resource/9xs2-f89t.json')

#Get df metadata
list(df)

['school_id',
 'name_of_school',
 'elementary_or_high_school',
 'street_address',
 'city',
 'state',
 'zip_code',
 'phone_number',
 'link_',
 'network_manager',
 'collaborative_name',
 'adequate_yearly_progress_made_',
 'track_schedule',
 'cps_performance_policy_status',
 'cps_performance_policy_level',
 'healthy_schools_certified_',
 'safety_icon_',
 'safety_score',
 'family_involvement_icon',
 'family_involvement_score',
 'environment_icon_',
 'environment_score',
 'instruction_icon_',
 'instruction_score',
 'leaders_icon_',
 'leaders_score_',
 'teachers_icon_',
 'teachers_score',
 'parent_engagement_icon_',
 'parent_engagement_score',
 'parent_environment_icon',
 'parent_environment_score',
 'average_student_attendance',
 'rate_of_misconducts_per_100_students_',
 'average_teacher_attendance',
 'individualized_education_program_compliance_rate_',
 'pk_2_literacy',
 'pk_2_math_',
 'gr3_5_grade_level_math',
 'gr3_5_grade_level_read_',
 'gr3_5_keep_pace_read_',
 'gr3_5_keep_pace_math',
 'gr6_8_grade_level_math',
 'gr6_8_grade_level_read',
 'gr6_8_keep_pace_math',
 'gr6_8_keep_pace_read',
 'gr_8_explore_math',
 'gr_8_explore_read',
 'isat_exceeding_math_',
 'isat_exceeding_reading_',
 'isat_value_add_math',
 'isat_value_add_read',
 'isat_value_add_color_math',
 'isat_value_add_color_read',
 'students_taking_algebra',
 'students_passing_algebra',
 '_th_grade_explore_2009_',
 '_th_grade_explore_2010_',
 '_th_grade_plan_2009_',
 '_th_grade_plan_2010_',
 'net_change_explore_and_plan',
 '_th_grade_average_act_2011_',
 'net_change_plan_and_act',
 'college_eligibility_',
 'graduation_rate_',
 'college_enrollment_rate',
 'college_enrollment_number_of_students_',
 'general_services_route_',
 'freshman_on_track_rate',
 'rcdts_code',
 'x_coordinate',
 'y_coordinate',
 'latitude',
 'longitude',
 'community_area_number',
 'community_area_name',
 'ward',
 'police_district',
 'location',
 ':@computed_region_rpca_8um6',
 ':@computed_region_vrxf_vc4k',
 ':@computed_region_6mkv_f3dw',
 ':@computed_region_bdys_3d7i',
 ':@computed_region_43wa_7qmu',
 ':@computed_region_awaf_s7ux']

In [2]:
#Cut unnecessary columns
df.drop(columns=[ ':@computed_region_rpca_8um6',
 ':@computed_region_vrxf_vc4k',
 ':@computed_region_6mkv_f3dw',
 ':@computed_region_bdys_3d7i',
 ':@computed_region_43wa_7qmu',
 ':@computed_region_awaf_s7ux'], axis=1, inplace=True)

In [3]:
#Connect to SQL 
import psycopg2
import IPython
import pandas.io.sql as sqlio
import psycopg2

In [4]:
%load_ext sql
%sql postgresql+psycopg2://postgres:5677@/IBM_SQL

#Check connection with SQL query
%%sql
SELECT * FROM information_schema.tables

SyntaxError: invalid syntax (Temp/ipykernel_12664/935592840.py, line 6)

In [5]:
%%sql
SELECT * FROM information_schema.tables

UsageError: Cell magic `%%sql` not found.

In [6]:
%load_ext sql

In [7]:
#Check connection with SQL query
%%sql
SELECT * FROM information_schema.tables

SyntaxError: invalid syntax (Temp/ipykernel_12664/3274918757.py, line 3)

In [8]:
%sql postgresql+psycopg2://postgres:5677@/IBM_SQL

In [9]:
SELECT * FROM information_schema.tables

SyntaxError: invalid syntax (Temp/ipykernel_12664/3810724762.py, line 1)

In [10]:
%sql postgresql+psycopg2://postgres:5677@/IBM_SQL

In [11]:
SELECT * FROM information_schema.tables

SyntaxError: invalid syntax (Temp/ipykernel_12664/3810724762.py, line 1)

In [12]:
%%sql
SELECT * FROM information_schema.tables

 * postgresql+psycopg2://postgres:***@/IBM_SQL
200 rows affected.

[('IBM_SQL', 'public', 'job_history', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'locations', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'df', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'employees', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'departments', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'jobs', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'petrescue', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statistic', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_type', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'book', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'chicago', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_policy', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_authid', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'public', 'international_student_test_scores', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_shadow', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_settings', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_hba_file_rules', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_file_settings', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_config', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'public', 'chicago_socioeconomic_data', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_user_mapping', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_replication_origin_status', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_subscription', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_user_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_xact_user_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_attribute', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_proc', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_class', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_attrdef', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_constraint', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_all_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_sys_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_user_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_all_indexes', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_inherits', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_index', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_operator', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_opfamily', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_opclass', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_am', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_amop', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_amproc', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_language', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_largeobject_metadata', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_aggregate', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statistic_ext', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_rewrite', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_trigger', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_event_trigger', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_description', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_cast', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_enum', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_namespace', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_conversion', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_depend', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_database', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_db_role_setting', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_tablespace', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_pltemplate', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_auth_members', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_shdepend', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_shdescription', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_ts_config', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_ts_config_map', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_ts_dict', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_ts_parser', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_ts_template', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_extension', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_foreign_data_wrapper', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_foreign_server', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_foreign_table', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_replication_origin', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_default_acl', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_init_privs', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_seclabel', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_shseclabel', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_collation', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_partitioned_table', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_range', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_transform', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_sequence', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_publication', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_publication_rel', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_subscription_rel', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_roles', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_locks', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_group', 'VIEW', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_user', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_policies', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_rules', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_views', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_matviews', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_indexes', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_sequences', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stats', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_publication_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_cursors', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_available_extensions', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_available_extension_versions', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_prepared_xacts', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_prepared_statements', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_seclabels', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_timezone_abbrevs', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_timezone_names', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_all_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_xact_all_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_sys_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_xact_sys_tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_sys_indexes', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_user_indexes', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_all_indexes', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_sys_indexes', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_user_indexes', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_all_sequences', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_sys_sequences', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_statio_user_sequences', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_activity', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_replication', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_wal_receiver', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_subscription', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_ssl', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_replication_slots', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_database', 'VIEW', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_database_conflicts', 'VIEW', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_user_functions', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_xact_user_functions', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_archiver', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_bgwriter', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_stat_progress_vacuum', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_user_mappings', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'pg_catalog', 'pg_largeobject', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'information_schema', 'information_schema_catalog_name', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'attributes', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'applicable_roles', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'administrable_role_authorizations', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'check_constraint_routine_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'character_sets', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'check_constraints', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'collations', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'collation_character_set_applicability', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'column_domain_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'column_privileges', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'routine_privileges', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'column_udt_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'columns', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'constraint_column_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'role_routine_grants', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'constraint_table_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'domain_constraints', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'domain_udt_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'routines', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'domains', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'enabled_roles', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'sql_parts', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'information_schema', 'key_column_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'schemata', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'parameters', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'referential_constraints', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'sql_languages', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'information_schema', 'role_column_grants', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'sequences', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'sql_features', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'information_schema', 'sql_implementation_info', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'information_schema', 'sql_packages', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'information_schema', 'sql_sizing', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'information_schema', 'sql_sizing_profiles', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('IBM_SQL', 'information_schema', 'view_routine_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'table_constraints', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'table_privileges', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'foreign_table_options', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'role_table_grants', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'view_table_usage', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'tables', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'transforms', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'triggered_update_columns', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'foreign_data_wrappers', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'triggers', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'views', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'udt_privileges', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'role_udt_grants', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'usage_privileges', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'data_type_privileges', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('IBM_SQL', 'information_schema', 'role_usage_grants', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),

In [13]:
from sqlalchemy import create_engine

#export dataframe to SQL as table
engine = create_engine('postgresql://postgres:5677@/IBM_SQL')

In [14]:
pd.set_option('max_columns', None)

In [15]:
df['link_'] = df['link_'].astype('str')

In [16]:
df['link_'] = df['link_'].str.replace("{'url': ","")
df['link_'] = df['link_'].str.replace("}","")

C:\Users\ivan\AppData\Local\Temp/ipykernel_12664/2941691595.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['link_'] = df['link_'].str.replace("{'url': ","")
C:\Users\ivan\AppData\Local\Temp/ipykernel_12664/2941691595.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['link_'] = df['link_'].str.replace("}","")

In [17]:
for column in df:
    df[column] = df[column].apply(json.dumps)

In [18]:
df = df.replace('"', '', regex=True)

In [19]:
df.to_sql('chicago', engine)

ValueError: Table 'chicago' already exists.

In [20]:
%%sql 
drop table chicago

 * postgresql+psycopg2://postgres:***@/IBM_SQL
Done.

[]

In [21]:
%%sql 
drop table chicago

 * postgresql+psycopg2://postgres:***@/IBM_SQL
(psycopg2.errors.UndefinedTable) table "chicago" does not exist

[SQL: drop table chicago]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [22]:
#upload file 
df.to_sql('chicago', engine)

In [23]:
%%sql
select * from parent_engagement_score

 * postgresql+psycopg2://postgres:***@/IBM_SQL
(psycopg2.errors.UndefinedTable) relation "parent_engagement_score" does not exist
LINE 1: select * from parent_engagement_score
                      ^

[SQL: select * from parent_engagement_score]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [24]:
%%sql
select * from chicago limit 5

 * postgresql+psycopg2://postgres:***@/IBM_SQL
5 rows affected.

[(0, '610038', 'Abraham Lincoln Elementary School', 'ES', '615 W Kemper Pl ', 'Chicago', 'IL', '60614', '(773) 534-5720', "'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610038.pdf'", 'Fullerton Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 1', 'Yes', 'Very Strong', '99.0', 'Very Strong', '99', 'Strong', '74.0', 'Strong', '66.0', 'Strong', '65', 'Strong', '70', 'Strong', '56', 'Average', '47', '96.0', '2.0', '96.4', '95.8', '80.1', '43.3', '89.6', '84.9', '60.7', '62.6', '81.9', '85.2', '52', '62.4', '66.3', '77.9', '69.7', '64.4', '0.2', '0.9', 'Yellow', 'Green', '67.1', '54.5', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '813', '33', 'NDA', '150000000000000', '1171699.458', '1915829.428', '41.92449696', '-87.64452163', '7', 'LINCOLN PARK', '43', '18', '{latitude: 41.92449696, longitude: -87.64452163}'),
 (1, '610281', 'Adam Clayton Powell Paideia Community Academy Elementary School', 'ES', '7511 S South Shore Dr ', 'Chicago', 'IL', '60649', '(773) 535-6650', "'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610281.pdf'", 'Skyway Elementary Network', 'SOUTH SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', '54.0', 'Strong', '66', 'Strong', '74.0', 'Very Strong', '84.0', 'Strong', '63', 'Strong', '76', 'Weak', '46', 'Average', '50', '95.6', '15.7', '95.3', '100.0', '62.4', '51.7', '21.9', '15.1', '29', '42.8', '38.5', '27.4', '44.8', '42.7', '14.1', '34.4', '16.8', '16.5', '0.7', '1.4', 'Green', 'Green', '17.2', '27.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '521', '46', 'NDA', '150000000000000', '1196129.985', '1856209.466', '41.76032435', '-87.55673627', '43', 'SOUTH SHORE', '7', '4', '{latitude: 41.76032435, longitude: -87.55673627}'),
 (2, '610185', 'Adlai E Stevenson Elementary School', 'ES', '8010 S Kostner Ave ', 'Chicago', 'IL', '60652', '(773) 535-2280', "'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610185.pdf'", 'Midway Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 2', 'No', 'Strong', '61.0', 'NDA', 'NDA', 'Average', '50.0', 'Weak', '36.0', 'NDA', 'NDA', 'NDA', 'NDA', 'Average', '47', 'Weak', '41', '95.7', '2.3', '94.7', '98.3', '53.7', '26.6', '38.3', '34.7', '43.7', '57.3', '48.8', '39.2', '46.8', '44', '7.5', '21.9', '18.3', '15.5', '-0.9', '-1.0', 'Red', 'Red', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '1324', '44', 'NDA', '150000000000000', '1148427.165', '1851012.215', '41.74711093', '-87.73170248', '70', 'ASHBURN', '13', '8', '{latitude: 41.74711093, longitude: -87.73170248}'),
 (3, '609993', 'Agustin Lara Elementary Academy', 'ES', '4619 S Wolcott Ave ', 'Chicago', 'IL', '60609', '(773) 535-4389', "'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609993.pdf'", 'Pershing Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 1', 'No', 'Average', '56.0', 'Average', '44', 'Average', '45.0', 'Weak', '37.0', 'Strong', '65', 'Average', '48', 'Average', '53', 'Strong', '58', '95.5', '10.4', '95.8', '100.0', '76.9', 'NDA', '26', '24.7', '61.8', '49.7', '39.2', '27.2', '69.7', '60.6', '9.1', '18.2', '11.1', '9.6', '0.9', '2.4', 'Green', 'Green', '42.9', '25', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '556', '42', 'NDA', '150000000000000', '1164504.29', '1873959.199', '41.8097569', '-87.6721446', '61', 'NEW CITY', '20', '9', '{latitude: 41.8097569, longitude: -87.6721446}'),
 (4, '610513', 'Air Force Academy High School', 'HS', '3630 S Wells St ', 'Chicago', 'IL', '60609', '(773) 535-1590', "'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610513.pdf'", 'Southwest Side High School Network', 'SOUTHWEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'Yes', 'Average', '49.0', 'Strong', '60', 'Strong', '60.0', 'Average', '55.0', 'Average', '45', 'Average', '54', 'Average', '53', 'Average', '49', '93.3', '15.6', '96.9', '100.0', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NaN', 'NaN', 'NaN', 'NaN', 'NDA', 'NDA', 'NDA', 'NDA', '14.6', '14.8', 'NDA', '16', '1.4', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '302', '40', '91.8', '150000000000000', '1175177.622', '1880745.126', '41.82814609', '-87.63279369', '34', 'ARMOUR SQUARE', '11', '9', '{latitude: 41.82814609, longitude: -87.63279369}')]

In [25]:
%%sql
select parent_engagement_score from chicago limit 5

 * postgresql+psycopg2://postgres:***@/IBM_SQL
5 rows affected.

[('56',), ('46',), ('47',), ('53',), ('53',)]

In [26]:
%%sql
select avg(parent_engagement_score) from chicago limit 5

 * postgresql+psycopg2://postgres:***@/IBM_SQL
(psycopg2.errors.UndefinedFunction) function avg(text) does not exist
LINE 1: select avg(parent_engagement_score) from chicago limit 5
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: select avg(parent_engagement_score) from chicago limit 5]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [27]:
%%sql
UPDATE table SET value=NULL WHERE value=NDA

 * postgresql+psycopg2://postgres:***@/IBM_SQL
(psycopg2.errors.SyntaxError) syntax error at or near "table"
LINE 1: UPDATE table SET value=NULL WHERE value=NDA
               ^

[SQL: UPDATE table SET value=NULL WHERE value=NDA]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [28]:
%%sql
df = df.replace('NDA', 'NULL', regex=True)

 * postgresql+psycopg2://postgres:***@/IBM_SQL
(psycopg2.errors.UndefinedColumn) column "value" does not exist
LINE 1: UPDATE chicago SET value=NULL WHERE value=NDA
                                            ^

[SQL: UPDATE chicago SET value=NULL WHERE value=NDA]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [29]:
df = df.replace('NDA', 'NULL', regex=True)

In [30]:
drop table if exists chicago

SyntaxError: invalid syntax (Temp/ipykernel_12664/2072905368.py, line 1)

In [31]:
%%sql 
drop table if exists chicago

 * postgresql+psycopg2://postgres:***@/IBM_SQL
Done.

[]

In [32]:
df.to_sql('chicago', engine)

In [33]:
%%sql
select parent_engagement_score from chicago limit 5

 * postgresql+psycopg2://postgres:***@/IBM_SQL
5 rows affected.

[('56',), ('46',), ('47',), ('53',), ('53',)]

In [34]:
%%sql
select avg(parent_engagement_score) from chicago limit 5

 * postgresql+psycopg2://postgres:***@/IBM_SQL
(psycopg2.errors.UndefinedFunction) function avg(text) does not exist
LINE 1: select avg(parent_engagement_score) from chicago limit 5
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: select avg(parent_engagement_score) from chicago limit 5]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [35]:
%%sql 
select column_name, data_type, character_maximum_length, column_default, is_nullable
from INFORMATION_SCHEMA.COLUMNS where table_name = 'chicago';

 * postgresql+psycopg2://postgres:***@/IBM_SQL
80 rows affected.

[('index', 'bigint', None, None, 'YES'),
 ('school_id', 'text', None, None, 'YES'),
 ('name_of_school', 'text', None, None, 'YES'),
 ('elementary_or_high_school', 'text', None, None, 'YES'),
 ('street_address', 'text', None, None, 'YES'),
 ('city', 'text', None, None, 'YES'),
 ('state', 'text', None, None, 'YES'),
 ('zip_code', 'integer', None, None, 'YES'),
 ('phone_number', 'text', None, None, 'YES'),
 ('link_', 'text', None, None, 'YES'),
 ('network_manager', 'text', None, None, 'YES'),
 ('collaborative_name', 'text', None, None, 'YES'),
 ('adequate_yearly_progress_made_', 'text', None, None, 'YES'),
 ('track_schedule', 'text', None, None, 'YES'),
 ('cps_performance_policy_status', 'text', None, None, 'YES'),
 ('cps_performance_policy_level', 'text', None, None, 'YES'),
 ('healthy_schools_certified_', 'text', None, None, 'YES'),
 ('safety_icon_', 'text', None, None, 'YES'),
 ('safety_score', 'text', None, None, 'YES'),
 ('family_involvement_icon', 'text', None, None, 'YES'),
 ('family_involvement_score', 'text', None, None, 'YES'),
 ('environment_icon_', 'text', None, None, 'YES'),
 ('environment_score', 'real', None, None, 'YES'),
 ('instruction_icon_', 'text', None, None, 'YES'),
 ('instruction_score', 'text', None, None, 'YES'),
 ('leaders_icon_', 'text', None, None, 'YES'),
 ('leaders_score_', 'integer', None, None, 'YES'),
 ('teachers_icon_', 'text', None, None, 'YES'),
 ('teachers_score', 'text', None, None, 'YES'),
 ('parent_engagement_icon_', 'text', None, None, 'YES'),
 ('parent_engagement_score', 'text', None, None, 'YES'),
 ('parent_environment_icon', 'text', None, None, 'YES'),
 ('parent_environment_score', 'text', None, None, 'YES'),
 ('average_student_attendance', 'text', None, None, 'YES'),
 ('rate_of_misconducts_per_100_students_', 'text', None, None, 'YES'),
 ('average_teacher_attendance', 'text', None, None, 'YES'),
 ('individualized_education_program_compliance_rate_', 'text', None, None, 'YES'),
 ('pk_2_literacy', 'text', None, None, 'YES'),
 ('pk_2_math_', 'text', None, None, 'YES'),
 ('gr3_5_grade_level_math', 'text', None, None, 'YES'),
 ('gr3_5_grade_level_read_', 'text', None, None, 'YES'),
 ('gr3_5_keep_pace_read_', 'text', None, None, 'YES'),
 ('gr3_5_keep_pace_math', 'text', None, None, 'YES'),
 ('gr6_8_grade_level_math', 'text', None, None, 'YES'),
 ('gr6_8_grade_level_read', 'text', None, None, 'YES'),
 ('gr6_8_keep_pace_math', 'text', None, None, 'YES'),
 ('gr6_8_keep_pace_read', 'text', None, None, 'YES'),
 ('gr_8_explore_math', 'text', None, None, 'YES'),
 ('gr_8_explore_read', 'text', None, None, 'YES'),
 ('isat_exceeding_math_', 'text', None, None, 'YES'),
 ('isat_exceeding_reading_', 'text', None, None, 'YES'),
 ('isat_value_add_math', 'text', None, None, 'YES'),
 ('isat_value_add_read', 'text', None, None, 'YES'),
 ('isat_value_add_color_math', 'text', None, None, 'YES'),
 ('isat_value_add_color_read', 'text', None, None, 'YES'),
 ('students_taking_algebra', 'text', None, None, 'YES'),
 ('students_passing_algebra', 'text', None, None, 'YES'),
 ('_th_grade_explore_2009_', 'text', None, None, 'YES'),
 ('_th_grade_explore_2010_', 'text', None, None, 'YES'),
 ('_th_grade_plan_2009_', 'text', None, None, 'YES'),
 ('_th_grade_plan_2010_', 'text', None, None, 'YES'),
 ('net_change_explore_and_plan', 'text', None, None, 'YES'),
 ('_th_grade_average_act_2011_', 'text', None, None, 'YES'),
 ('net_change_plan_and_act', 'text', None, None, 'YES'),
 ('college_eligibility_', 'text', None, None, 'YES'),
 ('graduation_rate_', 'text', None, None, 'YES'),
 ('college_enrollment_rate', 'text', None, None, 'YES'),
 ('college_enrollment_number_of_students_', 'text', None, None, 'YES'),
 ('general_services_route_', 'text', None, None, 'YES'),
 ('freshman_on_track_rate', 'text', None, None, 'YES'),
 ('rcdts_code', 'text', None, None, 'YES'),
 ('x_coordinate', 'text', None, None, 'YES'),
 ('y_coordinate', 'text', None, None, 'YES'),
 ('latitude', 'text', None, None, 'YES'),
 ('longitude', 'text', None, None, 'YES'),
 ('community_area_number', 'text', None, None, 'YES'),
 ('community_area_name', 'text', None, None, 'YES'),
 ('ward', 'text', None, None, 'YES'),
 ('police_district', 'text', None, None, 'YES'),
 ('location', 'text', None, None, 'YES')]

In [36]:
%%sql 
update chicago
set safety_score_ = NULL
WHERE safety_score = 'NaN';

 * postgresql+psycopg2://postgres:***@/IBM_SQL
(psycopg2.errors.UndefinedColumn) column "safety_score_" of relation "chicago" does not exist
LINE 1: update chicago set safety_score_ = NULL
                           ^

[SQL: update chicago set safety_score_ = NULL
WHERE safety_score = 'NaN';]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [37]:
%%sql 
alter table chicago alter column safety_score type integer  USING (safety_score::integer);

 * postgresql+psycopg2://postgres:***@/IBM_SQL

DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "99.0"

[SQL: alter table chicago alter column safety_score type integer  USING (safety_score::integer);]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

In [38]:
%%sql 
update chicago
set safety_score = NULL
WHERE safety_score = 'NaN';

 * postgresql+psycopg2://postgres:***@/IBM_SQL
53 rows affected.

[]

In [39]:
%%sql 
alter table chicago alter column safety_score type integer  USING (safety_score::integer);

 * postgresql+psycopg2://postgres:***@/IBM_SQL

DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "99.0"

[SQL: alter table chicago alter column safety_score type integer  USING (safety_score::integer);]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

In [40]:
alter table chicago alter column safety_score type integer  USING (safety_score::integer);

SyntaxError: invalid syntax (Temp/ipykernel_12664/1431485659.py, line 1)

In [41]:
%%sql 
Select max(safety_score) from chicago;

 * postgresql+psycopg2://postgres:***@/IBM_SQL
1 rows affected.

[(99,)]

In [42]:
%%sql
Select name_of_school, safety_score from chicago
where safety_score = (Select max(safety_score) from chicago);

 * postgresql+psycopg2://postgres:***@/IBM_SQL
19 rows affected.

[('Abraham Lincoln Elementary School', 99),
 ('Alexander Graham Bell Elementary School', 99),
 ('Annie Keller Elementary Gifted Magnet School', 99),
 ('Edgar Allan Poe Elementary Classical School', 99),
 ('Edgebrook Elementary School', 99),
 ('Ellen Mitchell Elementary School', 99),
 ('LaSalle Elementary Language Academy', 99),
 ('Mary E Courtenay Elementary Language Arts Center', 99),
 ('Northside Learning Center High School', 99),
 ('Norwood Park Elementary School', 99),
 ('Northside College Preparatory High School', 99),
 ('Sauganash Elementary School', 99),
 ('Stephen Decatur Classical Elementary School', 99),
 ('Talman Elementary School', 99),
 ('Wildwood Elementary School', 99),
 ('Augustus H Burley Elementary School', 99),
 ('James E McDade Elementary Classical School', 99),
 ('James G Blaine Elementary School', 99),
 ('Oriole Park Elementary School', 99)]

In [43]:
%%sql
Select name_of_school, average_student_attendance from chicago

 * postgresql+psycopg2://postgres:***@/IBM_SQL
566 rows affected.

[('Abraham Lincoln Elementary School', 96.0),
 ('Adam Clayton Powell Paideia Community Academy Elementary School', 95.6),
 ('Agustin Lara Elementary Academy', 95.5),
 ('Air Force Academy High School', 93.3),
 ('Albany Park Multicultural Academy', 97.0),
 ('Alessandro Volta Elementary School', 96.4),
 ('Alexander Graham Bell Elementary School', 96.3),
 ('Alexander Graham Elementary School', 92.5),
 ('Alexander Hamilton Elementary School', 95.3),
 ('Alfred David Kohn Elementary School', 90.1),
 ('Alfred Nobel Elementary School', 94.6),
 ('Amelia Earhart Options for Knowledge Elementary School', 96.3),
 ('Ames Middle School', 94.3),
 ('Amos Alonzo Stagg Elementary School', 91.4),
 ('Andrew Carnegie Elementary School', 94.6),
 ('Anna R. Langford Community Academy', 91.8),
 ('Annie Keller Elementary Gifted Magnet School', 97.5),
 ('Ana Roque de Duprey Elementary School', 95.4),
 ('Arthur E Canty Elementary School', 96.1),
 ('Ashburn Community Elementary School', 95.5),
 ('Avalon Park Elementary School', 92.1),
 ('Arthur A Libby Elementary School', 90.8),
 ('Belmont-Cragin Elementary School', 95.3),
 ('Benito Juarez Community Academy High School', 83.7),
 ('Benjamin E Mays Elementary Academy', 95.5),
 ('Bernhard Moos Elementary School', 93.0),
 ('Beulah Shoesmith Elementary School', 94.7),
 ('Benjamin Banneker Elementary School', 91.3),
 ('Betsy Ross Elementary School', 88.9),
 ('Bronzeville Scholastic Academy High School', 92.3),
 ('Burnham Elementary Inclusive Academy', 95.5),
 ('Calmeca Academy of Fine Arts and Dual Language', 96.5),
 ('Carl Schurz High School', 81.2),
 ('Carl von Linne Elementary School', 95.8),
 ('Carrie Jacobs Bond Elementary School', 91.7),
 ('Carter G Woodson South Elementary School', 91.9),
 ('Cesar E Chavez Multicultural Academic Center Elementary School', 95.1),
 ('Charles Allen Prosser Career Academy High School', 86.0),
 ('Charles Gates Dawes Elementary School', 95.7),
 ('Charles N Holden Elementary School', 94.9),
 ('Charles P Caldwell Academy of Math & Science Elementary School', 92.7),
 ('Charles P Steinmetz Academic Centre High School', 79.2),
 ('Charles R Darwin Elementary School', 95.6),
 ('Charles S Brownell Elementary School', 92.8),
 ('Charles S Deneen Elementary School', 93.8),
 ('Charles Sumner  Math & Science Community Acad Elementary School', 93.9),
 ('Chicago Academy High School', 93.1),
 ('Chicago High School for Agricultural Sciences', 92.8),
 ('Chicago Vocational Career Academy High School', 68.8),
 ('Christian Ebinger Elementary School', 95.9),
 ('Christian Fenger Academy High School', 74.4),
 ('Clara Barton Elementary School', 91.7),
 ('Claremont Academy Elementary School', 92.5),
 ('Collins Academy High School', 91.4),
 ('Columbia Explorers Elementary Academy', 95.4),
 ('Crispus Attucks Elementary School', 95.2),
 ('Crown Community Academy of Fine Arts Center Elementary School', 92.5),
 ('Daniel Boone Elementary School', 95.5),
 ('Christopher Columbus Elementary School', 95.5),
 ('Countee Cullen Elementary School', 94.1),
 ('Daniel S Wentworth Elementary School', 91.6),
 ('Daniel Webster Elementary School', 94.8),
 ('DeWitt Clinton Elementary School', 95.3),
 ('Donald Morrill Math & Science Elementary School', 93.4),
 ('Daniel Hale Williams Prep School of Medicine', 91.3),
 ('Daniel J Corkery Elementary School', 94.7),
 ('Dunne Technology Academy', 94.6),
 ('Durkin Park Elementary School', 95.4),
 ('Dvorak Technology Academy', 94.2),
 ('Dyett High School', 62.5),
 ('Edgar Allan Poe Elementary Classical School', 97.6),
 ('Edgebrook Elementary School', 96.9),
 ('Douglas Taylor Elementary School', 95.1),
 ('Dumas Technology Academy', 92.5),
 ('Edward A Bouchet Math & Science Academy Elementary School', 92.9),
 ('Edward C Delano Elementary School', 93.4),
 ('Edward Coles Elementary Language Academy', 95.1),
 ('Edward Jenner Elementary Academy of the Arts', 88.9),
 ('Edward N Hurley Elementary School', 95.4),
 ('Edward Tilden Career Community Academy High School', 78.4),
 ('Edmond Burke Elementary School', 89.3),
 ('Elaine O Goodlow Elementary Magnet School', 91.6),
 ('Elizabeth Peabody Elementary School', 95.2),
 ('Eliza Chappell Elementary School', 95.1),
 ('Ellen H Richards Career Academy High School', 90.6),
 ('Ellen Mitchell Elementary School', 95.5),
 ('Emil G Hirsch Metropolitan High School', 84.8),
 ('Emiliano Zapata Elementary Academy', 96.6),
 ('Emmett Louis Till Math and Science Academy', 88.0),
 ('Enrico Fermi Elementary School', 89.9),
 ('Eric Solorio Academy High School', 92.2),
 ('Eugene Field Elementary School', 96.8),
 ('Evergreen Academy Middle School', 96.1),
 ('Fairfield Elementary Academy', 93.4),
 ('Ernst Prussing Elementary School', 95.4),
 ('Federico Garcia Lorca Elementary School', 96.8),
 ('Ferdinand Peck Elementary School', 96.3),
 ('Fernwood Elementary School', 93.4),
 ('Florence Nightingale Elementary School', 95.6),
 ('Foster Park Elementary School', 93.7),
 ('Francisco I Madero Middle School', 95.1),
 ('Francis M McKay Elementary School', 93.5),
 ('Francis Parkman Elementary School', 90.6),
 ('Frank I Bennett Elementary School', 92.5),
 ('Frank W Gunsaulus Elementary Scholastic Academy', 96.6),
 ('Frazier Prospective IB Magnet Elementary School', 96.8),
 ('Frederic Chopin Elementary School', 96.9),
 ('Francis W Parker Elementary Community Academy', 91.9),
 ('Friedrich W von Steuben Metropolitan Science High School', 87.0),
 ('Gage Park High School', 72.5),
 ('Galileo Math & Science Scholastic Academy Elementary School', 95.0),
 ('Garrett A Morgan Elementary School', 92.0),
 ('George Armstrong International Studies Elementary School', 96.3),
 ('George B Swift Elementary Specialty School', 96.3),
 ('George F Cassell Elementary School', 94.4),
 ('Friedrich Ludwig Jahn Elementary School', 94.7),
 ('George H Corliss High School', 71.3),
 ('George Washington Elementary School', 95.5),
 ('George Washington High School', 80.2),
 ('George Westinghouse High School', 93.6),
 ('George Manierre Elementary School', 91.0),
 ('George W Tilton Elementary School', 91.4),
 ('Gerald Delgado Kanoon Elementary Magnet School', 95.9),
 ('Greater Lawndale High School For Social Justice', 87.5),
 ('Grover Cleveland Elementary School', 95.0),
 ('Hannah G Solomon Elementary School', 95.8),
 ('Hawthorne Elementary Scholastic Academy', 96.9),
 ('Helen M Hefferan Elementary School', 93.8),
 ('Helge A Haugan Elementary School', 96.2),
 ('Henry Clay Elementary School', 95.2),
 ('Harold Washington Elementary School', 96.1),
 ('Henry R Clissold Elementary School', 95.1),
 ('Hiram H Belding Elementary School', 95.0),
 ('Hope College Preparatory High School', 72.2),
 ('Horace Mann Elementary School', 92.6),
 ('Hyde Park Academy High School', 70.5),
 ('Horace Greeley Elementary School', 95.9),
 ('Irene C. Hernandez Middle School for the Advancement of Science', 95.5),
 ('Irma C Ruiz Elementary School', 95.5),
 ('Jacqueline B Vaughn Occupational High School', 87.6),
 ('James B Farnsworth Elementary School', 94.2),
 ('Infinity Math Science and Technology High School', 92.2),
 ('James Otis Elementary School', 95.5),
 ('James Ward Elementary School', 97.8),
 ('James Weldon Johnson Elementary School', 94.7),
 ('Jane Addams Elementary School', 96.0),
 ('Jane A Neil Elementary School', 88.9),
 ('Jean D Lafayette Elementary School', 94.1),
 ('Jensen Elementary Scholastic Academy', 93.1),
 ('Johann W von Goethe Elementary School', 95.8),
 ('Jean Baptiste Beaubien Elementary School', 95.7),
 ('Jesse Sherwood Elementary School', 92.0),
 ('John Barry Elementary School', 95.1),
 ('John B Drake Elementary School', 93.8),
 ('John Calhoun North Elementary School', 95.9),
 ('John C Burroughs Elementary School', 95.6),
 ('John C Coonley Elementary School', 95.9),
 ('John C Dore Elementary School', 95.6),
 ('John Charles Haines Elementary School', 98.4),
 ('John D Shoop Math-Science Technical Academy Elementary School', 93.2),
 ('John F Eberhart Elementary School', 95.3),
 ('John Fiske Elementary School', 92.9),
 ('John F Kennedy High School', 83.0),
 ('John Foster Dulles Elementary School', 94.1),
 ('John Hancock College Preparatory High School', 78.2),
 ('John Harvard Elementary School of Excellence', 93.0),
 ('John H Hamline Elementary School', 94.4),
 ('John J Audubon Elementary School', 96.2),
 ('John L Marsh Elementary School', 95.7),
 ('John Marshall Metropolitan High School', 74.1),
 ('John Milton Gregory Elementary School', 95.2),
 ('John P Altgeld Elementary School', 91.9),
 ('John Spry Elementary Community School', 96.2),
 ('John T McCutcheon Elementary School', 94.0),
 ('John M Smyth Elementary School', 92.4),
 ('Johnnie Colemon Elementary Academy', 95.9),
 ('John T Pirie Fine Arts & Academic Center Elementary School', 93.5),
 ('John W Garvy Elementary School', 95.3),
 ('John Whistler Elementary School', 92.4),
 ('Jonathan Burr Elementary School', 95.9),
 ('Jordan Elementary Community School', 95.6),
 ('Jose De Diego Elementary Community Academy', 95.0),
 ('Joseph Brennemann Elementary School', 96.5),
 ('Joseph E Gary Elementary School', 96.1),
 ('Jonathan Y Scammon Elementary School', 95.9),
 ('Josephine C Locke Elementary School', 95.5),
 ('Joseph Jungman Elementary School', 96.4),
 ('Joseph Kellman Corporate Community Elementary School', 95.2),
 ('Joshua D Kershaw Elementary School', 94.8),
 ('Josiah Pickard Elementary School', 95.8),
 ('Julia Ward Howe Elementary School of Excellence', 96.0),
 ('Joseph Lovett Elementary School', 95.4),
 ('Kelvyn Park High School', 74.4),
 ('Langston Hughes Elementary School', 90.0),
 ('LaSalle Elementary Language Academy', 96.8),
 ('LaSalle II Magnet Elementary School', 95.1),
 ('Laughlin Falconer Elementary School', 96.1),
 ('Kate S Buckingham Special Education Center', 83.4),
 ('Kate S Kellogg Elementary School', 96.3),
 ('Lenart Elementary Regional Gifted Center', 97.4),
 ('Leslie Lewis Elementary School', 91.8),
 ('Lincoln Park High School', 84.6),
 ('Little Village Elementary School', 96.7),
 ('Lorenz Brentano Math & Science Academy Elementary School', 94.7),
 ('Leif Ericson Elementary Scholastic Academy', 94.7),
 ('Lionel Hampton Fine & Performing Arts Elementary School', 95.0),
 ('Lyman A Budlong Elementary School', 95.4),
 ('Mancel Talcott Elementary School', 95.8),
 ('Manley Career Academy High School', 66.8),
 ('Mariano Azuela Elementary School', 95.5),
 ('Marie Sklodowska Curie Metropolitan High School', 85.0),
 ('Marine Military Math and Science Academy ', 91.3),
 ('Mark Sheridan Elementary Math & Science Academy', 96.8),
 ('Mark Twain Elementary School', 96.3),
 ('Martin A Ryerson Elementary School', 95.5),
 ('Marvin Camras Elementary School', 95.1),
 ('Mary Mapes Dodge Elementary Renaissance Academy', 94.4),
 ('Mary McLeod Bethune Elementary School', 93.3),
 ('Matthew Gallistel Elementary Language Academy', 95.1),
 ('Mary E Courtenay Elementary Language Arts Center', 94.9),
 ('Michael M Byrne Elementary School', 94.6),
 ('Mildred I Lavizzo Elementary School', 91.5),
 ('Minnie Mars Jamieson Elementary School', 95.7),
 ('Miriam G Canter Middle School', 91.4),
 ('Morton School of Excellence', 93.6),
 ('Medgar Evers Elementary School', 94.9),
 ('Mount Vernon Elementary School', 93.3),
 ('Myra Bradwell Communications Arts & Sciences Elementary School', 92.1),
 ('Nathan Hale Elementary School', 94.5),
 ('National Teachers Elementary Academy', 94.7),
 ('Moses Montefiore Special Elementary School', 80.4),
 ('New Millennium High School of Health at Bowen', 75.6),
 ('Newton Bateman Elementary School', 96.2),
 ('Nicholson Technology Academy', 93.4),
 ('North River Elementary School', 95.6),
 ('Neal F Simeon Career Academy High School', 78.6),
 ('Northside Learning Center High School', 89.8),
 ('Norwood Park Elementary School', 95.5),
 ('Ole A Thorp Elementary Scholastic Academy', 96.4),
 ('Oliver S Westcott Elementary School', 92.6),
 ('Northside College Preparatory High School', 95.7),
 ('Oscar DePriest Elementary School', 92.7),
 ('Park Manor Elementary School', 94.9),
 ('Patrick Henry Elementary School', 95.1),
 ('Paul Cuffe Math-Science Technology Academy Elementary School', 93.6),
 ('Paul Laurence Dunbar Career Academy High School', 76.9),
 ('Orville T Bright Elementary School', 92.2),
 ('Oscar F Mayer Elementary School', 95.0),
 ('Percy L Julian High School', 74.6),
 ('Perkins Bass Elementary School', 92.1),
 ('Pershing West Middle School', 96.2),
 ('Peter A Reinberg Elementary School', 95.8),
 ('Philip Rogers Elementary School', 96.4),
 ('Pilsen Elementary Community Academy', 96.0),
 ('Phillip D Armour Elementary School', 93.9),
 ('Pulaski International Academy Elmentary School', 96.1),
 ('Rachel Carson Elementary School', 97.6),
 ('Ray Graham Training Center High School', 86.3),
 ('Richard Edwards Elementary School', 95.3),
 ('Richard J Daley Elementary Academy', 94.9),
 ('Richard J Oglesby Elementary School', 94.4),
 ('Portage Park Elementary School', 94.2),
 ('Roald Amundsen High School', 81.1),
 ('Robert Fulton Elementary School', 95.1),
 ('Robert H Lawrence Elementary School', 90.7),
 ('Robert L Grimes Elementary School', 95.2),
 ('Roberto Clemente Community Academy High School', 69.6),
 ('Roger C Sullivan High School', 81.6),
 ('Ronald Brown Elementary Community Academy', 93.8),
 ('Ronald E McNair Elementary School', 90.7),
 ('Rosario Castellanos Elementary School', 96.3),
 ('Roswell B Mason Elementary School', 92.4),
 ('Rufus M Hitch Elementary School', 95.1),
 ('Salmon P Chase Elementary School', 95.4),
 ('Samuel Gompers Fine Arts Options Elementary School', 93.6),
 ('Scott Joplin Elementary School', 95.0),
 ('Sidney Sawyer Elementary School', 96.8),
 ('South Loop Elementary School', 95.3),
 ('Sauganash Elementary School', 96.3),
 ('Simon Guggenheim Elementary School', 90.9),
 ('Sir Miles Davis Magnet Elementary Academy', 93.0),
 ('Songhai Elementary Learning Institute', 89.5),
 ('Spencer Technology Academy', 92.5),
 ('Stephen Decatur Classical Elementary School', 96.2),
 ('Stephen F Gale Elementary Community Academy', 92.1),
 ('Stephen K Hayt Elementary School', 95.6),
 ('Stephen T Mather High School', 87.6),
 ('Talman Elementary School', 96.2),
 ('Spry Community Links High School', 95.6),
 ('Stone Elementary Scholastic Academy', 96.4),
 ('TEAM Englewood Community Academy High School', 87.3),
 ('Telpochcalli Elementary School', 95.4),
 ('Thomas Chalmers Specialty Elementary School', 94.4),
 ('Thomas Hoyne Elementary School', 94.8),
 ('Theodore Herzl Elementary School', 90.8),
 ('Thomas Kelly High School', 89.3),
 ('Turner-Drew Elementary Language Academy', 95.8),
 ('Uplift Community High School', 88.7),
 ('Victor Herbert Elementary School', 92.8),
 ('Virgil Grissom Elementary School', 95.5),
 ('Walter L Newberry Math & Science Academy Elementary School', 95.1),
 ('Thomas J Waters Elementary School', 96.1),
 ('Thurgood Marshall Middle School', 94.0),
 ('Walter Q Gresham Elementary School', 95.5),
 ('Wells Community Academy High School', 74.1),
 ('Wendell Smith Elementary School', 92.1),
 ('Walter Payton College Preparatory High School', 93.4),
 ('Walter Reed Elementary School', 92.4),
 ('West Pullman Elementary School', 91.2),
 ('Whitney M Young Magnet High School', 94.6),
 ('Wildwood Elementary School', 96.2),
 ('Willa Cather Elementary School', 94.9),
 ('William Bishop Owen Scholastic Academy Elementary School', 96.9),
 ('William C Goudy Elementary School', 96.1),
 ('William C Reavis Math & Science Specialty Elementary School', 93.5),
 ('West Ridge Elementary School', 94.9),
 ('William E Dever Elementary School', 95.5),
 ('William F Finkl Elementary School', 95.2),
 ('William H Brown Elementary School', 92.8),
 ('William H Seward Communication Arts Academy Elementary School', 95.7),
 ('William H King Elementary School', 92.4),
 ('William J & Charles H Mayo Elementary School', 95.3),
 ('William J Onahan Elementary School', 95.7),
 ('William K New Sullivan Elementary School', 90.3),
 ('William Rainey Harper High School', 73.0),
 ('William Jones College Preparatory High School', 93.8),
 ('William W Carter Elementary School', 91.2),
 ('World Language Academy High School', 91.6),
 ('Wolfgang A Mozart Elementary School', 95.2),
 ('Adlai E Stevenson Elementary School', 95.7),
 ('Albert G Lane Technical High School', 96.3),
 ('Albert R Sabin Elementary Magnet School', 94.7),
 ('Alcott High School for the Humanities', 92.7),
 ('Alexander von Humboldt Elementary School', 92.5),
 ('Alex Haley Elementary Academy', 94.9),
 ('Alice L Barnard Computer Math & Science Center Elementary School', 95.6),
 ('Al Raby High School', 80.3),
 ('Ambrose Plamondon Elementary School', 96.9),
 ('Andrew Jackson Elementary Language Academy', 97.4),
 ('A.N. Pritzker School', 94.6),
 ('Anthony Overton Elementary School', 90.5),
 ('Arna Wendell Bontemps Elementary School', 94.2),
 ('Arnold Mireles Elementary Academy', 92.8),
 ('Arthur Dixon Elementary School', 94.8),
 ('Asa Philip Randolph Elementary School', 92.1),
 ('Augustus H Burley Elementary School', 96.5),
 ('Austin Business and Entrepreneurship Academy High School', 76.0),
 ('Austin O Sexton Elementary School', 90.5),
 ('Austin Polytechnical Academy High School', 70.1),
 ('Bret Harte Elementary School', 94.2),
 ('Brian Piccolo Elementary Specialty School', 90.6),
 ('Brighton Park Elementary School', 96.3),
 ('Burnside Elementary Scholastic Academy', 94.9),
 ('Carroll-Rosenwald Specialty Elementary School', 94.8),
 ('Charles Evans Hughes Elementary School', 94.4),
 ('Charles G Hammond Elementary School', 95.3),
 ('Charles H Wacker Elementary School', 93.4),
 ('Charles Kozminski Elementary Community Academy', 92.0),
 ('Charles R Henderson Elementary School', 89.2),
 ('Charles W Earle Elementary School', 93.8),
 ('Chicago Academy Elementary School', 96.3),
 ('Chicago Military Academy High School', 90.3),
 ('Daniel R Cameron Elementary School', 92.6),
 ('David G Farragut Career Academy High School', 86.1),
 ('Dewey Elementary Academy of Fine Arts', 90.7),
 ('Edison Park Elementary School', 96.1),
 ('Edward Beasley Elementary Magnet Academic Center', 95.0),
 ('Edward K Ellington Elementary School', 93.3),
 ('Edward White Elementary Career Academy', 93.8),
 ('Edwin G Foreman High School', 84.3),
 ('Elihu Yale Elementary School', 89.7),
 ('Eli Whitney Elementary School', 95.8),
 ('Elizabeth H Sutherland Elementary School', 95.6),
 ('Ella Flagg Young Elementary School', 94.3),
 ('Esmond Elementary School', 92.9),
 ('Everett McKinley Dirksen Elementary School', 95.9),
 ('Florence B Price Elementary School', 90.0),
 ('Fort Dearborn Elementary School', 93.4),
 ('Francis Scott Key Elementary School', 91.9),
 ('Frank L Gillespie Elementary School', 91.9),
 ('Franklin Elementary Fine Arts Center', 95.9),
 ('Frank W Reilly Elementary School', 97.0),
 ('Frederick A Douglass Academy High School', 79.2),
 ('Frederick Funston Elementary School', 94.7),
 ('Genevieve Melody Elementary School', 92.1),
 ('George B McClellan Elementary School', 93.2),
 ('George M Pullman Elementary School', 93.5),
 ('George Rogers Clark Elementary School', 93.9),
 ('George Washington Carver Military Academy High School', 91.6),
 ('George Washington Carver Primary School', 90.9),
 ('George W Curtis Elementary School', 93.8),
 ('Graeme Stewart Elementary School', 95.2),
 ('Granville T Woods Math & Science Academy Elementary School', 91.9),
 ('Guglielmo Marconi Elementary Community Academy', 91.5),
 ('Gurdon S Hubbard High School', 89.3),
 ('Gwendolyn Brooks College Preparatory Academy High School', 87.1),
 ('Hanson Park Elementary School', 95.0),
 ('Harriet Beecher Stowe Elementary School', 93.8),
 ('Harriet E Sayre Elementary Language Academy', 96.2),
 ('Helen Peirce International Studies Elementary School', 96.7),
 ('Henry H Nash Elementary School', 95.1),
 ('Henry O Tanner Elementary School', 91.8),
 ('Horatio May Elementary Community Academy', 91.9),
 ('Hyman G Rickover Naval Academy High School', 92.9),
 ('Ida B Wells Preparatory Elementary Academy', 93.2),
 ('Ignance Paderewski Elementary Learning Academy', 92.1),

In [44]:
%%sql
Select name_of_school, average_student_attendance from chicago
order by average_student_attendance
limit 10

 * postgresql+psycopg2://postgres:***@/IBM_SQL
10 rows affected.

[('Richard T Crane Technical Preparatory High School', 57.9),
 ('Barbara Vick Early Childhood & Family Center', 60.9),
 ('Dyett High School', 62.5),
 ('Wendell Phillips Academy High School', 63.0),
 ('Orr Academy High School', 66.3),
 ('Manley Career Academy High School', 66.8),
 ('Chicago Vocational Career Academy High School', 68.8),
 ('Roberto Clemente Community Academy High School', 69.6),
 ('Austin Polytechnical Academy High School', 70.1),
 ('Hyde Park Academy High School', 70.5)]

In [45]:
%%sql
Select name_of_school, average_student_attendance from chicago
order by average_student_attendance DESC
limit 10;

 * postgresql+psycopg2://postgres:***@/IBM_SQL
10 rows affected.

[('Velma F Thomas Early Childhood Center', nan),
 ('John Charles Haines Elementary School', 98.4),
 ('James Ward Elementary School', 97.8),
 ('Orozco Fine Arts & Sciences Elementary School', 97.6),
 ('Rachel Carson Elementary School', 97.6),
 ('Edgar Allan Poe Elementary Classical School', 97.6),
 ('Annie Keller Elementary Gifted Magnet School', 97.5),
 ('Lenart Elementary Regional Gifted Center', 97.4),
 ('Andrew Jackson Elementary Language Academy', 97.4),
 ('Disney II Magnet School', 97.3)]

In [46]:
%%sql
Select name_of_school, average_student_attendance 
from chicago
where average_student_attendance < 70;

 * postgresql+psycopg2://postgres:***@/IBM_SQL
8 rows affected.

[('Chicago Vocational Career Academy High School', 68.8),
 ('Dyett High School', 62.5),
 ('Manley Career Academy High School', 66.8),
 ('Roberto Clemente Community Academy High School', 69.6),
 ('Richard T Crane Technical Preparatory High School', 57.9),
 ('Wendell Phillips Academy High School', 63.0),
 ('Barbara Vick Early Childhood & Family Center', 60.9),
 ('Orr Academy High School', 66.3)]

In [ ]:
select college_enrollment_rate from chicago